# Generated by Django 5.0 on 2024-08-31 01:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0002_remove_proyecto_estatus_proyecto'),
    ]

    operations = [
        migrations.RenameField(
            model_name='detalleproyecto',
            old_name='pasaporte',
            new_name='numero_pasaporte',
        ),
    ]
