# Generated by Django 5.0 on 2024-08-31 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
        ('procesos', '0003_rename_pasaporte_detalleproyecto_numero_pasaporte'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proyecto',
            name='id_empresa',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='id_empresa_pm',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='id_empresa_po',
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_empresa_ini', to='maestros.cliente', verbose_name='Empresa INI'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_cliente_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_empresa_pm', to='maestros.cliente', verbose_name='Empresa PM'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_cliente_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_empresa_po', to='maestros.cliente', verbose_name='Empresa PO'),
        ),
        migrations.AlterField(
            model_name='detalleproyecto',
            name='aeropuerto_cercano',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Aeropuesto Cercano'),
        ),
        migrations.AlterField(
            model_name='detalleproyecto',
            name='dob',
            field=models.DateField(blank=True, null=True, verbose_name='D.O.B'),
        ),
    ]
