# Generated by Django 5.0 on 2024-09-07 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0004_remove_proyecto_id_empresa_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='observaciones_proyecto',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Observaciones'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='ticket_hotel',
            field=models.BooleanField(choices=[(True, 'Pagamos Nosotros'), (False, 'Paga la Naviera')], default=True, verbose_name='Ticket'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.SmallIntegerField(choices=[(1, 'Dry Dock'), (2, 'Sealing'), (3, 'Survey'), (4, 'Survey - Dry Dock'), (5, 'Survey - Sealing')], default=1, verbose_name='Tipo'),
        ),
    ]
