# Generated by Django 5.0 on 2024-10-26 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0006_proyecto_gerente_proyecto_proyecto_orden_compra'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyecto',
            name='companhia',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Compañía'),
        ),
    ]
