# Generated by Django 5.0 on 2024-10-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0007_detalleproyecto_companhia'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyecto',
            name='fecha_exp_visa',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Exp. Visa'),
        ),
    ]
