# Generated by Django 5.0 on 2024-10-26 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procesos', '0008_detalleproyecto_fecha_exp_visa'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyecto',
            name='email_persona',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='e-MAIL Principal'),
        ),
    ]
