# Generated by Django 5.0 on 2024-08-30 18:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0016_remove_detalleproyecto_id_proyecto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('estatus_proyecto', models.BooleanField(choices=[(True, 'Activo'), (False, 'Inactivo')], default=True, verbose_name='Estatus')),
                ('condicion_proyecto', models.SmallIntegerField(choices=[(1, 'En Preparación'), (2, 'En Proceso'), (3, 'Suspendido'), (4, 'Finalizado')], default=1, verbose_name='Condición')),
                ('tipo_proyecto', models.SmallIntegerField(choices=[(1, 'Dry Dock'), (2, 'Sealing'), (3, 'Survey'), (4, 'Survey - Dry Dock'), (5, 'Survey - Sealing')], default=1, verbose_name='Condición')),
                ('codigo_proyecto', models.CharField(blank=True, max_length=60, null=True, verbose_name='Código')),
                ('nombre_proyecto', models.CharField(blank=True, max_length=60, null=True, verbose_name='Proyecto')),
                ('fecha_registro_proyecto', models.DateField(blank=True, null=True, verbose_name='Fecha Registro')),
                ('fecha_inicio_proyecto', models.DateField(blank=True, null=True, verbose_name='Fecha Inicio')),
                ('fecha_final_proyecto', models.DateField(blank=True, null=True, verbose_name='Fecha Final')),
                ('ticket_hotel', models.BooleanField(choices=[(True, 'Pagamos Nosotros'), (False, 'Paga la Naviera')], default=True, verbose_name='Estatus')),
                ('ubicacion_inicial', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ubicación Inicial')),
                ('ubicacion_final', models.CharField(blank=True, max_length=60, null=True, verbose_name='Ubicación Final')),
                ('observaciones_proyecto', models.CharField(blank=True, max_length=60, null=True, verbose_name='Proyecto')),
                ('id_empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_empresa_ini', to='maestros.empresa', verbose_name='Empresa INI')),
            ],
            options={
                'db_table': 'proyecto',
            },
        ),
        migrations.CreateModel(
            name='DetalleProyecto',
            fields=[
                ('usuario', models.CharField(blank=True, max_length=20, null=True)),
                ('estacion', models.CharField(blank=True, max_length=20, null=True)),
                ('fcontrol', models.CharField(blank=True, max_length=22, null=True)),
                ('id_detalle_proyecto', models.AutoField(primary_key=True, serialize=False)),
                ('id_proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='procesos.proyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
