# Generated by Django 5.0 on 2024-08-30 20:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0017_alter_persona_id_proyecto2_and_more'),
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleproyecto',
            name='aeropuerto_cercano',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Aeropuesto Cercano'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='apellido_persona',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Apellidos'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='codigo_persona',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='Código'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='confirmado',
            field=models.BooleanField(choices=[(True, 'Confirmado'), (False, 'No Confirmado')], default=True, verbose_name='Confirmado'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='dob',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='D.O.B'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='fecha_exp_pasaporte',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Exp. Pas.'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='fecha_final_persona',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Final'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='fecha_inicio_persona',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Inicio'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='nombre_persona',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nombres'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='numero_visa',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número Visa'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='pais_ciudadania',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Puesto'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='pasaporte',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Pasaporte'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='puesto_trabajo',
            field=models.CharField(blank=True, max_length=40, null=True, verbose_name='Puesto'),
        ),
        migrations.AddField(
            model_name='detalleproyecto',
            name='tipo_visa',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Tipo Visa'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_empresa_pm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_empresa_pm', to='maestros.empresa', verbose_name='Empresa PM'),
        ),
        migrations.AddField(
            model_name='proyecto',
            name='id_empresa_po',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='id_empresa_po', to='maestros.empresa', verbose_name='Empresa PO'),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='observaciones_proyecto',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Proyecto'),
        ),
        migrations.AlterModelTable(
            name='detalleproyecto',
            table='detalle_proyecto',
        ),
    ]
