# Generated by Django 5.0 on 2024-08-30 20:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('maestros', '0001_initial'),
        ('procesos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='id_proyecto1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecto1', to='procesos.proyecto'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_proyecto2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecto2', to='procesos.proyecto'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_proyecto3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='proyecto3', to='procesos.proyecto'),
        ),
        migrations.AddField(
            model_name='personatarifa',
            name='id_persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.persona'),
        ),
        migrations.AddField(
            model_name='persona',
            name='id_tipodoc_identidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='maestros.tipodocumentoidentidad', verbose_name='Tipo de Documento'),
        ),
        migrations.AddField(
            model_name='subzona',
            name='id_zona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='maestros.zona'),
        ),
    ]
