# Generated by Django 5.0 on 2024-10-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maestros', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='numero_visa1',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Visa 1'),
        ),
        migrations.AddField(
            model_name='persona',
            name='numero_visa2',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Número de Visa 2'),
        ),
    ]
